"""initial tables

Revision ID: 68930effe622
Revises: 
Create Date: 2026-05-26 12:44:07.487068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '68930effe622'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('connector_type', sa.String(length=50), nullable=False),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('auth_token_hash', sa.String(length=255), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='agent_meeting_dev'
    )
    op.create_table('rooms',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('topic', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='draft', nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='agent_meeting_dev'
    )
    op.create_table('decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('proposer_agent_id', sa.Uuid(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['proposer_agent_id'], ['agent_meeting_dev.agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['agent_meeting_dev.rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='agent_meeting_dev'
    )
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_meeting_dev.agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['agent_meeting_dev.messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['agent_meeting_dev.rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='agent_meeting_dev'
    )
    op.create_table('room_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_meeting_dev.agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['agent_meeting_dev.rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='agent_meeting_dev'
    )
    op.create_table('action_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('decision_id', sa.Uuid(), nullable=True),
    sa.Column('assignee_agent_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignee_agent_id'], ['agent_meeting_dev.agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['decision_id'], ['agent_meeting_dev.decisions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['agent_meeting_dev.rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='agent_meeting_dev'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('action_items', schema='agent_meeting_dev')
    op.drop_table('room_members', schema='agent_meeting_dev')
    op.drop_table('messages', schema='agent_meeting_dev')
    op.drop_table('decisions', schema='agent_meeting_dev')
    op.drop_table('rooms', schema='agent_meeting_dev')
    op.drop_table('agents', schema='agent_meeting_dev')
    # ### end Alembic commands ###
