"""add_users_and_api_keys_tables

Revision ID: ce67480fa092
Revises: 68930effe622
Create Date: 2026-05-27 21:42:08.573716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce67480fa092'
down_revision: Union[str, Sequence[str], None] = '68930effe622'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('connector_type', sa.String(length=50), nullable=False),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('auth_token_hash', sa.String(length=255), nullable=True),
    sa.Column('auth_token', sa.String(length=255), nullable=True),
    sa.Column('owner_id', sa.String(length=255), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_token'),
    schema='agent_meeting_dev'
    )
    op.create_table('rooms',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('topic', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='draft', nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['agent_meeting_dev.users.id'], ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    schema='agent_meeting_dev'
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('role', sa.String(length=20), server_default='user', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    schema='agent_meeting_dev'
    )
    op.create_table('api_keys',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('key_prefix', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), server_default='["read","write"]', nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['agent_meeting_dev.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='agent_meeting_dev'
    )
    op.create_table('decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('proposer_agent_id', sa.Uuid(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proposer_agent_id'], ['agent_meeting_dev.agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['agent_meeting_dev.rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='agent_meeting_dev'
    )
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_meeting_dev.agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['agent_meeting_dev.messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['agent_meeting_dev.rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='agent_meeting_dev'
    )
    op.create_table('room_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_meeting_dev.agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['agent_meeting_dev.rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='agent_meeting_dev'
    )
    op.create_table('action_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('decision_id', sa.Uuid(), nullable=True),
    sa.Column('assignee_agent_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_agent_id'], ['agent_meeting_dev.agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['decision_id'], ['agent_meeting_dev.decisions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['agent_meeting_dev.rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='agent_meeting_dev'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('action_items', schema='agent_meeting_dev')
    op.drop_table('room_members', schema='agent_meeting_dev')
    op.drop_table('messages', schema='agent_meeting_dev')
    op.drop_table('decisions', schema='agent_meeting_dev')
    op.drop_table('api_keys', schema='agent_meeting_dev')
    op.drop_table('users', schema='agent_meeting_dev')
    op.drop_table('rooms', schema='agent_meeting_dev')
    op.drop_table('agents', schema='agent_meeting_dev')
    # ### end Alembic commands ###
